// <auto-generated />
namespace WebNhaHang.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ussers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ussers));
        
        string IMigrationMetadata.Id
        {
            get { return "202305210757203_ussers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
